"""Export the production notebook cells as a standalone Python pipeline."""

from __future__ import annotations

import json
from pathlib import Path


HERE = Path(__file__).resolve().parent
NOTEBOOK = HERE.parent / "navelmaker2_refactored.ipynb"
OUTPUT = HERE / "pipeline_program.py"


HEADER = r'''"""Standalone Steps 1-16 pipeline exported from navelmaker2_refactored.ipynb.

This file is generated by export_notebook_pipeline.py. Edit the notebook or the
exporter, then regenerate this file instead of editing generated code by hand.
"""

from __future__ import annotations

import argparse
import builtins
import json as _progress_json
import math
import re as _progress_re
import sys
from pathlib import Path as _ProgressPath


def _parse_arguments():
    parser = argparse.ArgumentParser(description="Prepare a novel simulation.")
    parser.add_argument("--novel", required=True, help="Path to the source novel TXT file.")
    parser.add_argument("--percent", type=float, default=100.0)
    parser.add_argument("--chunk-size", type=int, default=2000)
    parser.add_argument("--overlap", type=int, default=300)
    return parser.parse_args()


ARGS = _parse_arguments()
_ORIGINAL_PRINT = builtins.print
_STEP9_RANGE = (10.0, 68.0)
_STEP11_RANGE = (72.0, 80.0)


def emit_progress(percent, label, current=None, total=None):
    payload = {
        "percent": max(0.0, min(100.0, float(percent))),
        "label": str(label),
    }
    if current is not None:
        payload["current"] = int(current)
    if total is not None:
        payload["total"] = int(total)
    _ORIGINAL_PRINT(
        "@@PROGRESS " + _progress_json.dumps(payload, ensure_ascii=False),
        flush=True,
    )


def _pipeline_print(*values, **kwargs):
    text = " ".join(str(value) for value in values)
    chunk_match = _progress_re.search(r"Step 9: chunk (\d+)/(\d+)", text)
    batch_match = _progress_re.search(r"Step 11: batch (\d+)/(\d+)", text)
    if chunk_match:
        current, total = map(int, chunk_match.groups())
        start, end = _STEP9_RANGE
        emit_progress(
            start + (end - start) * current / max(1, total),
            f"Step 9 graph extraction: chunk {current}/{total}",
            current,
            total,
        )
    elif batch_match:
        current, total = map(int, batch_match.groups())
        start, end = _STEP11_RANGE
        emit_progress(
            start + (end - start) * current / max(1, total),
            f"Step 11 identity resolution: batch {current}/{total}",
            current,
            total,
        )
    _ORIGINAL_PRINT(*values, **kwargs)


builtins.print = _pipeline_print
emit_progress(1, "Reading source novel")
'''


CUSTOM_PROJECT_INIT = r'''
file_path = str(_ProgressPath(ARGS.novel).expanduser().resolve())
novel_text = read_novel_txt(file_path)
project_data = {
    "file_path": file_path,
    "raw_text": novel_text,
}
emit_progress(3, "Splitting novel into sections")
'''


CUSTOM_CHUNK_BUILD = r'''
chunks = build_chunks_from_sections(
    project_data["sections"],
    chunk_size=ARGS.chunk_size,
    overlap=ARGS.overlap,
)
project_data["chunks"] = chunks
emit_progress(6, f"Built {len(chunks)} chunks")
'''


CUSTOM_STEP9_OVERRIDE = r'''
if not 0 < ARGS.percent <= 100:
    raise ValueError("--percent must be greater than 0 and at most 100.")
STEP9_CHUNK_LIMIT = max(
    1,
    math.ceil(len(project_data["chunks"]) * ARGS.percent / 100.0),
)
STEP9_FORCE_REBUILD = False
print(
    f"Selected {STEP9_CHUNK_LIMIT}/{len(project_data['chunks'])} chunks "
    f"({ARGS.percent:g}% requested)."
)
emit_progress(9, "Starting graph extraction")
'''


CELL_SEQUENCE = [
    ("cell", 0),
    ("cell", 1),
    ("text", CUSTOM_PROJECT_INIT),
    ("cell", 4),
    ("cell", 5),
    ("cell", 6),
    ("text", CUSTOM_CHUNK_BUILD),
    # Keep retrieval functions available without building unused indexes.
    ("cell", 8),
    ("cell", 10),
    ("cell", 12),
    ("cell", 13),
    ("cell", 14),
    ("cell", 15),
    ("cell", 16),
    ("progress", (7, "Building ontology")),
    ("cell", 19),
    ("cell", 21),
    ("text", CUSTOM_STEP9_OVERRIDE),
    ("cell", 22),
    ("cell", 23),
    ("progress", (69, "Building mention and alias index")),
    ("cell", 25),
    ("cell", 26),
    ("cell", 27),
    ("progress", (72, "Resolving canonical entities")),
    ("cell", 29),
    ("cell", 30),
    ("cell", 31),
    ("progress", (81, "Normalizing graph relations")),
    ("cell", 33),
    ("progress", (86, "Building structured world graph")),
    ("cell", 35),
    ("progress", (89, "Building character state database")),
    ("cell", 37),
    ("progress", (94, "Building world database")),
    ("cell", 39),
    ("progress", (97, "Building agent profiles")),
    ("cell", 41),
]


FOOTER = r'''
emit_progress(100, "Preparation complete")
print("All preparation outputs were created successfully.")
'''


LLM_CLIENT_BLOCK = '''LLM_API_KEY = os.getenv("NOVEL_LLM_API_KEY", "lm-studio")'''
LLM_CLIENT_REPLACEMENT = '''LLM_API_KEY = (
    os.getenv("NOVEL_LLM_API_KEY", "").strip() or "lm-studio"
)'''
LLM_INIT_BLOCK = '''llm_client = (
    OpenAI(base_url=LLM_BASE_URL, api_key=LLM_API_KEY)
    if OpenAI is not None
    else None
)'''
LLM_INIT_REPLACEMENT = '''llm_client = None
if OpenAI is not None:
    try:
        llm_client = OpenAI(
            base_url=LLM_BASE_URL,
            api_key=LLM_API_KEY,
        )
    except Exception as error:
        print(
            "OpenAI SDK client unavailable; using standard HTTP transport:",
            error,
        )'''

STEP9_RESULT_BLOCK = '''    result = {
        "chunk_id": chunk_id,
        "chunk_index": chunk_index,
        "nodes": nodes,'''
STEP9_RESULT_REPLACEMENT = '''    result = {
        "chunk_id": chunk_id,
        "chunk_index": chunk_index,
        "chunk_text_hash": hashlib.sha256(
            chunk_text.encode("utf-8")
        ).hexdigest(),
        "nodes": nodes,'''

STEP9_STATE_BLOCK = '''def new_step9_state(chunks, ontology):
    chunk_manifest = [
        {
            "chunk_id": get_chunk_id(chunk, index),
            "text_hash": hashlib.sha256(
                get_chunk_text(chunk).encode("utf-8")
            ).hexdigest(),
        }
        for index, chunk in enumerate(chunks)
    ]
    return {
        "schema_version": STEP9_SCHEMA_VERSION,
        "step": 9,
        "purpose": "Ontology-constrained local graph extraction.",
        "ontology_fingerprint": stable_json_hash(ontology),
        "chunk_manifest_fingerprint": stable_json_hash(chunk_manifest),
        "expected_chunk_count": len(chunks),
        "completed_chunk_count": 0,
        "complete": False,
        "results": [],
    }


def load_or_create_step9_state(chunks, ontology):
    expected = new_step9_state(chunks, ontology)
    if STEP9_FORCE_REBUILD or not STEP9_OUTPUT_PATH.exists():
        return expected

    existing = json.loads(STEP9_OUTPUT_PATH.read_text(encoding="utf-8"))
    if not isinstance(existing, dict) or existing.get("schema_version") != STEP9_SCHEMA_VERSION:
        if STEP9_RESET_LEGACY_OUTPUT:
            print("Legacy Step 9 output detected; rebuilding it with schema v2.")
            return expected
        raise ValueError("Legacy raw_graph_triples.json detected. Enable STEP9_RESET_LEGACY_OUTPUT.")

    for key in ("ontology_fingerprint", "chunk_manifest_fingerprint", "expected_chunk_count"):
        if existing.get(key) != expected.get(key):
            raise ValueError(
                f"Step 9 input changed ({key}). Set STEP9_FORCE_REBUILD=True to rebuild."
            )
    return existing'''

STEP9_STATE_REPLACEMENT = '''def step9_chunk_manifest(chunks):
    return [
        {
            "chunk_id": get_chunk_id(chunk, index),
            "text_hash": hashlib.sha256(
                get_chunk_text(chunk).encode("utf-8")
            ).hexdigest(),
        }
        for index, chunk in enumerate(chunks)
    ]


def new_step9_state(chunks, ontology):
    chunk_manifest = step9_chunk_manifest(chunks)
    return {
        "schema_version": STEP9_SCHEMA_VERSION,
        "step": 9,
        "purpose": "Ontology-constrained local graph extraction.",
        "source_text_fingerprint": hashlib.sha256(
            project_data["raw_text"].encode("utf-8")
        ).hexdigest(),
        "ontology_fingerprint": stable_json_hash(ontology),
        "chunk_manifest": chunk_manifest,
        "chunk_manifest_fingerprint": stable_json_hash(chunk_manifest),
        "expected_chunk_count": len(chunks),
        "completed_chunk_count": 0,
        "complete": False,
        "results": [],
    }


def step9_result_matches_chunk(result, chunk, chunk_index):
    current_hash = hashlib.sha256(
        get_chunk_text(chunk).encode("utf-8")
    ).hexdigest()
    saved_hash = clean_graph_text(result.get("chunk_text_hash"))
    if saved_hash:
        return saved_hash == current_hash

    # Migration for checkpoints created before chunk hashes were stored.
    haystack = normalized_evidence_text(get_chunk_text(chunk))
    evidence = [
        clean_graph_text(item.get("source_text"))
        for group in (result.get("nodes", []), result.get("edges", []))
        for item in group
        if clean_graph_text(item.get("source_text"))
    ]
    evidence.extend(
        clean_graph_text(item.get("text"))
        for item in result.get("uncertain", [])
        if clean_graph_text(item.get("text"))
    )
    return bool(evidence) and all(
        normalized_evidence_text(item) in haystack
        for item in evidence
    )


def load_or_create_step9_state(chunks, ontology):
    expected = new_step9_state(chunks, ontology)
    if STEP9_FORCE_REBUILD or not STEP9_OUTPUT_PATH.exists():
        return expected

    existing = json.loads(STEP9_OUTPUT_PATH.read_text(encoding="utf-8"))
    if not isinstance(existing, dict) or existing.get("schema_version") != STEP9_SCHEMA_VERSION:
        if STEP9_RESET_LEGACY_OUTPUT:
            print("Legacy Step 9 output detected; rebuilding it with schema v2.")
            return expected
        raise ValueError("Legacy raw_graph_triples.json detected. Enable STEP9_RESET_LEGACY_OUTPUT.")

    if existing.get("ontology_fingerprint") != expected["ontology_fingerprint"]:
        print("Step 9 ontology changed; starting a new extraction checkpoint.")
        return expected

    current_source = expected["source_text_fingerprint"]
    saved_source = existing.get("source_text_fingerprint")
    if saved_source and saved_source != current_source:
        print("Step 9 source novel changed; starting a new extraction checkpoint.")
        return expected

    chunk_by_id = {
        str(get_chunk_id(chunk, index)): (chunk, index)
        for index, chunk in enumerate(chunks)
    }
    reusable = []
    for result in existing.get("results", []):
        pair = chunk_by_id.get(str(result.get("chunk_id")))
        if pair is None:
            continue
        chunk, chunk_index = pair
        if not step9_result_matches_chunk(result, chunk, chunk_index):
            continue
        migrated = dict(result)
        migrated["chunk_text_hash"] = hashlib.sha256(
            get_chunk_text(chunk).encode("utf-8")
        ).hexdigest()
        reusable.append(migrated)

    expected["results"] = reusable
    expected["completed_chunk_count"] = len(reusable)
    print(
        "Step 9 resume:",
        f"reusing {len(reusable)} completed chunks; "
        f"{len(chunks) - len(reusable)} remain for this scope.",
    )
    return expected'''


def prepare_cell_source(cell_index, source):
    if cell_index == 16:
        if LLM_CLIENT_BLOCK not in source or LLM_INIT_BLOCK not in source:
            raise RuntimeError("Notebook LLM client block changed; update the exporter.")
        return source.replace(
            LLM_CLIENT_BLOCK,
            LLM_CLIENT_REPLACEMENT,
        ).replace(
            LLM_INIT_BLOCK,
            LLM_INIT_REPLACEMENT,
        )
    if cell_index == 22:
        if STEP9_RESULT_BLOCK not in source or STEP9_STATE_BLOCK not in source:
            raise RuntimeError("Notebook Step 9 blocks changed; update the exporter.")
        return source.replace(
            STEP9_RESULT_BLOCK,
            STEP9_RESULT_REPLACEMENT,
        ).replace(
            STEP9_STATE_BLOCK,
            STEP9_STATE_REPLACEMENT,
        )
    return source


def main():
    notebook = json.loads(NOTEBOOK.read_text(encoding="utf-8"))
    parts = [HEADER]
    for kind, value in CELL_SEQUENCE:
        if kind == "cell":
            source = "".join(notebook["cells"][value].get("source", []))
            source = prepare_cell_source(value, source)
            parts.append(f"\n\n# %% Notebook cell {value}\n{source.rstrip()}\n")
        elif kind == "progress":
            percent, label = value
            parts.append(f'\n\nemit_progress({percent}, {label!r})\n')
        else:
            parts.append(f"\n\n{value.strip()}\n")
    parts.append(FOOTER)
    OUTPUT.write_text("".join(parts), encoding="utf-8")
    print(f"Exported {OUTPUT} ({OUTPUT.stat().st_size:,} bytes)")


if __name__ == "__main__":
    main()
